apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: betapool
  namespace: rook
spec:
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: beta
provisioner: rook.io/block
parameters:
  pool: betapool

