apiVersion: ceph.rook.io/v1beta1
kind: Pool
metadata:
  name: betapool
  namespace: rook-ceph
spec:
  # The failure domain will spread the replicas of the data across different failure zones
  failureDomain: osd
  # The root of the crush hierarchy that will be used for the pool. If not set, will use "default".
  crushRoot: default
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: beta
provisioner: ceph.rook.io/block
parameters:
  pool: betapool
  clusterNamespace: rook-ceph
  fstype: xfs
