global:
  resolve_timeout: 10m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: zabbix
receivers:
  - name: zabbix
    webhook_configs:
      - url: http://alertmanager-zabbix-webhook:8080/alerts
        send_resolved: true
