apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
    name: quota
    namespace: monitoring
  spec:
    hard:
      configmaps: "100"
      limits.cpu: "8"
      limits.memory: 16Gi
      requests.cpu: "8"
      requests.memory: 16Gi
      requests.nvidia.com/gpu: "0"
      secrets: "100"
      services: "100"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

