auth_url = "https://keystone.api.cloud.ipnett.no/v3"
domain_name = "uninett.no"
tenant_name = "paastest.uninett.no"
region = "no-south-1"
node_flavor = "b.small"
coreos_image = "7a23b8ae-3aae-4f57-9382-cb5cfdb1f970"
