auth_url = "https://keystone.api.cloud.ipnett.no/v3"
domain_name = "uninett.no"
tenant_name = "paastest.uninett.no"
region = "no-south-1"
node_flavor = "b.small"
coreos_image = "d795bead-fa4e-4fab-954a-9c13676d4032"
