apiVersion: v1
kind: Pod
metadata:
  name: haproxy-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: haproxy-apiserver
      image: haproxy:1.5
      volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: config
          readOnly: true
  volumes:
    - name: config
      hostPath:
        path: /etc/kubernetes/haproxy-apiserver.cfg
