- name: Add API server HA proxy configuration file
  template:
    src: haproxy-apiserver.cfg
    dest: /etc/kubernetes/haproxy-apiserver.cfg
    owner: root
    group: root
    mode: 0644
- name: Add API server HA proxy Kubelet manifest
  copy:
    src: haproxy-apiserver.yaml
    dest: /etc/kubernetes/manifests/haproxy-apiserver.yaml
    owner: root
    group: root
    mode: 0644
