apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-scraper
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heapster-scraper
    spec:
      containers:
      - name: heapster-scraper
        image: registry.uninett.no/public/paas2-metric-scraper
        env:
          - name: GRAPHITE_SERVER
            value: {{ graphite_server }}
          - name: GRAPHITE_PREFIX
            value: kubernetes.{{ cluster_name }}
        command: ["/app/heapster_scraper.py"]
        args:
          - --scrape-url
          - http://heapster.kube-system.svc.cluster.local/api/v1/model
          - --graphite-prefix
          - $(GRAPHITE_PREFIX)
          - --graphite-server
          - $(GRAPHITE_SERVER)
