- name: Configure Prometheus and Alertmanager
  hosts: 127.0.0.1
  connection: local
  become: false
  vars_files:
    - vars.yaml
  roles:
    - prometheus_operator
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
