- name: Provider specific Kubernetes resources
  hosts: 127.0.0.1
  connection: local
  become: false
  roles:
    - aws
  vars_files:
  - vars.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"