apiVersion: v1
kind: ServiceAccount
metadata:
  name: controlplane-logshipper
  namespace: kube-system

---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: controlplane-logshipper
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
spec:
  hostPID: false
  hostIPC: false
  privileged: false
  hostNetwork: false
  allowedCapabilities:
  - KILL
  - CHOWN
  - FSETID
  - FOWNER
  - SETGID
  - SETUID
  - SETFCAP
  - SETPCAP
  - AUDIT_WRITE
  - NET_BIND_SERVICE
  requiredDropCapabilities:
  - MKNOD
  - DAC_OVERRIDE
  - NET_RAW
  - SYS_CHROOT
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - 'secret'
  - 'configMap'
  - 'hostPath'

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controlplane-logshipper
rules:
  - apiGroups:
    - extensions
    resources:
    - podsecuritypolicies
    resourceNames:
    - controlplane-logshipper
    verbs:
    - use
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controlplane-logshipper
subjects:
  - kind: ServiceAccount
    name: controlplane-logshipper
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: controlplane-logshipper
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uninett-ca-crt
  namespace: kube-system
data:
  uninett-ca-crt.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIEbzCCA1egAwIBAgIJAJAhu7l6dg+nMA0GCSqGSIb3DQEBBQUAMEoxCzAJBgNV
    BAYTAk5PMRMwEQYDVQQKEwpVTklORVRUIEFTMSYwJAYDVQQDEx1VTklORVRUIENl
    cnRpZmljYXRlIEF1dGhvcml0eTAeFw0xMDAyMDYwMDEyMzBaFw0yMDAyMDQwMDEy
    MzBaMEoxCzAJBgNVBAYTAk5PMRMwEQYDVQQKEwpVTklORVRUIEFTMSYwJAYDVQQD
    Ex1VTklORVRUIENlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEB
    BQADggEPADCCAQoCggEBAK2+21jlJLycaCgg6TBo+i37DkWvW4UR3ptLzQAQfBuO
    SfPBPG9zXhmn0z/gNWfpbAwETiW+2oTcSKz/XJ0Ej1dFnySNWBnNb6rOY7GrTAvk
    RfDbpacQATPwg9RnvBs4xR+6TGNLcYjcyEnjF+Xd29aRzH/rFkJHq2pM6rT5BpSc
    Q4n1DrB2y+E812UjDYhx8KnD9Zh+83wpa3tMRI5J9n7AuqrBThS4xudCAcJLMyu3
    KTEnBpRMRfduVyndPTJe+EVcp3XBip41Biza73ZFScqMDFfskc2jT3XV3Tz+0Act
    g56m+JirRtcQc8lP7o/P6BXTRmIfeXbHuX7/BSE+AXECAwEAAaOCAVYwggFSMB0G
    A1UdDgQWBBQlxqCOiIgff64MlbIUojA2QgTzTjB6BgNVHSMEczBxgBQlxqCOiIgf
    f64MlbIUojA2QgTzTqFOpEwwSjELMAkGA1UEBhMCTk8xEzARBgNVBAoTClVOSU5F
    VFQgQVMxJjAkBgNVBAMTHVVOSU5FVFQgQ2VydGlmaWNhdGUgQXV0aG9yaXR5ggkA
    kCG7uXp2D6cwDAYDVR0TBAUwAwEB/zAbBgNVHREEFDASgRBkcmlmdEB1bmluZXR0
    Lm5vMDgGA1UdHwQxMC8wLaAroCmGJ2h0dHA6Ly9jYS51bmluZXR0Lm5vL3VuaW5l
    dHQtY2EtY3JsLnBlbTAzBggrBgEFBQcBAQQnMCUwIwYIKwYBBQUHMAGGF2h0dHA6
    Ly9vY3NwLnVuaW5ldHQubm8vMBsGA1UdEgQUMBKBEGRyaWZ0QHVuaW5ldHQubm8w
    DQYJKoZIhvcNAQEFBQADggEBAA9/27nksOl8d7uwi8Ce0u8WOpwDnwUUdYu0/1U9
    1bG+bVxFL/rmenLVJJ9vaU0jxa/xHG2r8Q1RvIz1OqGX8XpbzB9cIB2Bj4kIJ+wg
    +pHroH9hmhJkf1gxMphtcZL3B2KAAc1B27ZchEJifFJuvL+wghAWVh0iwxhul5JO
    gDH0cXwvNyjRJjR70uvpU2YmRhNunqhU6hd89HPZpSybq5LU939i5HSnSgAsqQmO
    SCt0APlJNlJ/y5UWxMBO9ayycIuSHbORBJ8ZnXHw3yScbIEioqvAaDJNQUTNw8Pn
    n/dq6ffTELCFs/4QBOz7av0IxjnemYuCzgUZmb+YPhYKW+c=
    -----END CERTIFICATE-----

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: controlplane-logshipper
  namespace: kube-system
  labels:
    app: controlplane-logshipper
spec:
  template:
    metadata:
      labels:
        app: controlplane-logshipper
        name: controlplane-logshipper
    spec:
      serviceAccount: controlplane-logshipper
      terminationGracePeriodSeconds: 60
      containers:
      - image:  docker.elastic.co/beats/filebeat:5.6.3
        name: controlplane-logshipper
        imagePullPolicy: Always
        command: ["/usr/share/filebeat/filebeat"]
        args: ["-e", "-c", "/usr/share/filebeat/controlplane-logshipper.yml"]
        securityContext:
          runAsUser: 0
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 200m
            memory: 400Mi
          limits:
            cpu: 600m
            memory: 800Mi
        volumeMounts:
          - name: data
            mountPath: /data
          - name: container-data
            mountPath: /var/lib/docker/containers
          - name: filebeat-data
            mountPath: /var/lib/filebeat
          - name: audit-data
            mountPath: /var/log/apiserver
          - name: uninett-ca-crt
            mountPath: /etc/ssl/private
          - name: config
            mountPath: /usr/share/filebeat/controlplane-logshipper.yml
            subPath: controlplane-logshipper.yml
      volumes:
        - name: data
          hostPath:
            path: /var/log/containers
        - name: container-data
          hostPath:
            path: /var/lib/docker/containers
        - name: filebeat-data
          hostPath:
            path: /var/lib/filebeat
        - name: audit-data
          hostPath:
            path: /var/log/apiserver
        - name: uninett-ca-crt
          configMap:
            name: uninett-ca-crt
            items:
            - key: uninett-ca-crt.pem
              path: uninett-ca-crt.pem
        - name: config
          secret:
            secretName: controlplane-logshipper-config
            items:
            - key: controlplane-logshipper.yml
              path: controlplane-logshipper.yml



