apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: default
spec:
  limits:
  - defaultRequest:
      cpu: 100m
      memory: 200Mi
    default:
      cpu: 300m
      memory: 400Mi
    type: Container
