# This file is a workaround for kubectl not being able to access the
# swagger API descriptions. It should be fixed in version 1.6. See:
# https://github.com/kubernetes/kubernetes/commit/a209040ac8d78818fd98a058222764e7b3538657

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: discovery-workaround
rules:
- nonResourceURLs:
  - /swaggerapi
  - /swaggerapi/*
  verbs:
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: discovery-workaround
subjects:
- kind: Group
  name: system:authenticated
- kind: Group
  name: system:unauthenticated
roleRef:
  kind: ClusterRole
  name: discovery-workaround
  apiGroup: rbac.authorization.k8s.io
