apiVersion: v1
kind: ServiceAccount
metadata:
  name: journalbeat
  namespace: kube-system

---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: journalbeat
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
spec:
  hostPID: false
  hostIPC: false
  privileged: false
  hostNetwork: false
  allowedCapabilities:
  - KILL
  - CHOWN
  - FSETID
  - FOWNER
  - SETGID
  - SETUID
  - SETFCAP
  - SETPCAP
  - AUDIT_WRITE
  - NET_BIND_SERVICE
  requiredDropCapabilities:
  - MKNOD
  - DAC_OVERRIDE
  - NET_RAW
  - SYS_CHROOT
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - 'secret'
  - 'configMap'
  - 'hostPath'

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: journalbeat
rules:
  - apiGroups:
    - extensions
    resources:
    - podsecuritypolicies
    resourceNames:
    - journalbeat
    verbs:
    - use
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: journalbeat
subjects:
  - kind: ServiceAccount
    name: journalbeat
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: journalbeat
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uninett-ca-crt
  namespace: kube-system
data:
  uninett-ca-crt.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIEbzCCA1egAwIBAgIJAJAhu7l6dg+nMA0GCSqGSIb3DQEBBQUAMEoxCzAJBgNV
    BAYTAk5PMRMwEQYDVQQKEwpVTklORVRUIEFTMSYwJAYDVQQDEx1VTklORVRUIENl
    cnRpZmljYXRlIEF1dGhvcml0eTAeFw0xMDAyMDYwMDEyMzBaFw0yMDAyMDQwMDEy
    MzBaMEoxCzAJBgNVBAYTAk5PMRMwEQYDVQQKEwpVTklORVRUIEFTMSYwJAYDVQQD
    Ex1VTklORVRUIENlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEB
    BQADggEPADCCAQoCggEBAK2+21jlJLycaCgg6TBo+i37DkWvW4UR3ptLzQAQfBuO
    SfPBPG9zXhmn0z/gNWfpbAwETiW+2oTcSKz/XJ0Ej1dFnySNWBnNb6rOY7GrTAvk
    RfDbpacQATPwg9RnvBs4xR+6TGNLcYjcyEnjF+Xd29aRzH/rFkJHq2pM6rT5BpSc
    Q4n1DrB2y+E812UjDYhx8KnD9Zh+83wpa3tMRI5J9n7AuqrBThS4xudCAcJLMyu3
    KTEnBpRMRfduVyndPTJe+EVcp3XBip41Biza73ZFScqMDFfskc2jT3XV3Tz+0Act
    g56m+JirRtcQc8lP7o/P6BXTRmIfeXbHuX7/BSE+AXECAwEAAaOCAVYwggFSMB0G
    A1UdDgQWBBQlxqCOiIgff64MlbIUojA2QgTzTjB6BgNVHSMEczBxgBQlxqCOiIgf
    f64MlbIUojA2QgTzTqFOpEwwSjELMAkGA1UEBhMCTk8xEzARBgNVBAoTClVOSU5F
    VFQgQVMxJjAkBgNVBAMTHVVOSU5FVFQgQ2VydGlmaWNhdGUgQXV0aG9yaXR5ggkA
    kCG7uXp2D6cwDAYDVR0TBAUwAwEB/zAbBgNVHREEFDASgRBkcmlmdEB1bmluZXR0
    Lm5vMDgGA1UdHwQxMC8wLaAroCmGJ2h0dHA6Ly9jYS51bmluZXR0Lm5vL3VuaW5l
    dHQtY2EtY3JsLnBlbTAzBggrBgEFBQcBAQQnMCUwIwYIKwYBBQUHMAGGF2h0dHA6
    Ly9vY3NwLnVuaW5ldHQubm8vMBsGA1UdEgQUMBKBEGRyaWZ0QHVuaW5ldHQubm8w
    DQYJKoZIhvcNAQEFBQADggEBAA9/27nksOl8d7uwi8Ce0u8WOpwDnwUUdYu0/1U9
    1bG+bVxFL/rmenLVJJ9vaU0jxa/xHG2r8Q1RvIz1OqGX8XpbzB9cIB2Bj4kIJ+wg
    +pHroH9hmhJkf1gxMphtcZL3B2KAAc1B27ZchEJifFJuvL+wghAWVh0iwxhul5JO
    gDH0cXwvNyjRJjR70uvpU2YmRhNunqhU6hd89HPZpSybq5LU939i5HSnSgAsqQmO
    SCt0APlJNlJ/y5UWxMBO9ayycIuSHbORBJ8ZnXHw3yScbIEioqvAaDJNQUTNw8Pn
    n/dq6ffTELCFs/4QBOz7av0IxjnemYuCzgUZmb+YPhYKW+c=
    -----END CERTIFICATE-----

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: journalbeat
  namespace: kube-system
  labels:
    app: journalbeat
spec:
  template:
    metadata:
      labels:
        app: journalbeat
        name: journalbeat
    spec:
      serviceAccount: journalbeat
      terminationGracePeriodSeconds: 60
      containers:
      - image:  mheese/journalbeat:v5.5.2
        name: journalbeat
        imagePullPolicy: Always
        command: ["/journalbeat"]
        args: ["-e", "-c", "/etc/journalbeat.yml"]
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 200m
            memory: 400Mi
          limits:
            cpu: 600m
            memory: 800Mi
        volumeMounts:
          - name: data
            mountPath: /data
          - name: var-journal
            mountPath: /var/log/journal
          - name: run-journal
            mountPath: /run/log/journal
          - name: config
            mountPath: /etc/journalbeat.yml
            subPath: journalbeat.yml
          - name: machine-id
            mountPath: /etc/machine-id
          - name: uninett-ca-crt
            mountPath: /etc/ssl/private
      volumes:
        - name: data
          hostPath:
            path: /var/lib/journalbeat
        - name: var-journal
          hostPath:
            path: /var/log/journal
        - name: run-journal
          hostPath:
            path: /run/log/journal
        - name: machine-id
          hostPath:
            path: /etc/machine-id
        - name: uninett-ca-crt
          configMap:
            name: uninett-ca-crt
            items:
            - key: uninett-ca-crt.pem
              path: uninett-ca-crt.pem
        - name: config
          secret:
            secretName: journalbeat-config
            items:
            - key: journalbeat.yml
              path: journalbeat.yml



