apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-utils
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system-utils
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - update
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system-utils
subjects:
  - kind: ServiceAccount
    name: system-utils
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system-utils
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system-utils-view
subjects:
  - kind: ServiceAccount
    name: system-utils
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
