- name: Make etcd configuration folder
  file:
    state: directory
    path: /etc/etcd
    owner: root
    group: root
    mode: 0755
- name: Make etcd data folder
  file:
    state: directory
    path: /var/lib/etcd
    owner: root
    group: root
    mode: 0755
- name: Make etcd backups folder
  file:
    state: directory
    path: /var/backups/etcd
    owner: root
    group: root
    mode: 0755
- name: Add Etcd manifest
  template:
    src: etcd.yaml.j2
    dest: /etc/kubernetes/manifests/etcd.yaml
    owner: root
    group: root
    mode: 0644
  tags:
    - etcd_manifest
