- name: Add kube-scheduler manifest
  template:
    src: kube-scheduler.yaml.j2
    dest: /etc/kubernetes/manifests/kube-scheduler.yaml
    owner: root
    group: root
    mode: 0644
  tags: k8s_upgrade
